# Generated by Django 3.0.5 on 2020-04-04 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200404_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 14, 59, 38, 155921, tzinfo=utc)),
        ),
    ]
