# Generated by Django 3.0.5 on 2020-04-06 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200405_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 11, 54, 32, 241675, tzinfo=utc)),
        ),
    ]
